version: '3'

services:
  clickhouse-server:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-server
    container_name: clickhouse-server
    ports:
      - "9001:9000"
    volumes:
      - clickhouse-db-data-config:/etc/clickhouse-server
      - clickhouse-db-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-client:
    image: yandex/clickhouse-client:21.3.20
    hostname: clickhouse-client
    container_name: clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    volumes:
      - "${PWD}/hits_v1.tsv:/tmp/hits_v1.tsv"
      - "${PWD}/visits_v1.tsv:/tmp/visits_v1.tsv"
    depends_on:
      - clickhouse-server
      
volumes:
  clickhouse-db-data:
  clickhouse-db-data-config: