version: '3'

services:
  clickhouse-zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
      - "2182:2182"
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper

  clickhouse-01:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-01
    container_name: clickhouse-01
    ports:
      - "9001:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-1:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-02:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-02
    container_name: clickhouse-02
    ports:
      - "9002:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-2:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-03:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-03
    container_name: clickhouse-03
    ports:
      - "9003:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-03.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-3:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-04:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-04
    container_name: clickhouse-04
    ports:
      - "9004:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-04.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-4:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-05:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-05
    container_name: clickhouse-05
    ports:
      - "9005:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-05.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-5:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-06:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-06
    container_name: clickhouse-06
    ports:
      - "9006:9000"
    volumes:
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./config/macros/macros-06.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-db-data-6:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - clickhouse-zookeeper

  clickhouse-cluster-client:
    image: yandex/clickhouse-client:21.3.20
    hostname: clickhouse-client
    container_name: clickhouse-cluster-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    volumes:
      - "${PWD}/hits_v1.tsv:/tmp/hits_v1.tsv"
      - "${PWD}/visits_v1.tsv:/tmp/visits_v1.tsv"
    depends_on:
      - clickhouse-01
      - clickhouse-02
      - clickhouse-03
      - clickhouse-04
      - clickhouse-05
      - clickhouse-06

volumes:
  clickhouse-db-data-1:
  clickhouse-db-data-2:
  clickhouse-db-data-3:
  clickhouse-db-data-4:
  clickhouse-db-data-5:
  clickhouse-db-data-6: