version: '3.5'

services:
  scylla-1:
    image: scylladb/scylla:5.1.0
    container_name: scylla-1
    ports:
      - 9042:9042
    command: --smp 8 --memory 2G --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla:
        ipv4_address: 172.32.0.2
    volumes:
      - scylla-db-data-1:/var/lib/scylla

  scylla-2:
    image: scylladb/scylla:5.1.0
    container_name: scylla-2
    ports:
      - 9043:9042
    command: --seeds=172.32.0.2 ---smp 8 --memory 2G --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla:
        ipv4_address: 172.32.0.3
    volumes:
      - scylla-db-data-2:/var/lib/scylla

  scylla-3:
    image: scylladb/scylla:5.1.0
    container_name: scylla-3
    ports:
      - 9044:9042
    command: --seeds=172.32.0.2 --smp 8 --memory 2G --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla:
        ipv4_address: 172.32.0.4
    volumes:
      - scylla-db-data-3:/var/lib/scylla

networks:
  scylla:
    ipam:
      config:
        - subnet: 172.32.0.0/24

volumes:
  scylla-db-data-1:
  scylla-db-data-2:
  scylla-db-data-3: