version: '3.5'

services:
  consul1:
    container_name: consul1
    command: agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0
    hostname: consul1
    image: consul:1.12.3
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  consul2:
    container_name: consul2
    command: agent -server -retry-join consul1 -disable-host-node-id
    hostname: consul2
    image: consul:1.12.3
    expose:
      - "8400"
      - "8500"
      - "8600"
    depends_on:
      - consul1

  consul3:
    container_name: consul3
    command: agent -server -retry-join consul1 -disable-host-node-id
    hostname: consul3
    image: consul:1.12.3
    expose:
      - "8400"
      - "8500"
      - "8600"
    depends_on:
      - consul1