version: '3.5'

services:
  cassandra-1:
    image: cassandra:4.1
    container_name: cassandra-1
    ports:
      - 9042:9042
    networks:
      cassandra:
        ipv4_address: 172.22.0.2
    volumes:
      - cassandra-db-data-1:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cloudinfra
      - CASSANDRA_BROADCAST_ADDRESS=172.22.0.2
      - CASSANDRA_SEEDS=172.22.0.3,172.22.0.4

  cassandra-2:
    image: cassandra:4.1
    container_name: cassandra-2
    ports:
      - 9043:9042
    networks:
      cassandra:
        ipv4_address: 172.22.0.3
    volumes:
      - cassandra-db-data-2:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cloudinfra
      - CASSANDRA_BROADCAST_ADDRESS=172.22.0.3
      - CASSANDRA_SEEDS=172.22.0.2,172.22.0.4

  cassandra-3:
    image: cassandra:4.1
    container_name: cassandra-3
    ports:
      - 9044:9042
    networks:
      cassandra:
        ipv4_address: 172.22.0.4
    volumes:
      - cassandra-db-data-3:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cloudinfra
      - CASSANDRA_BROADCAST_ADDRESS=172.22.0.4
      - CASSANDRA_SEEDS=172.22.0.2,172.22.0.3

networks:
  cassandra:
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  cassandra-db-data-1:
  cassandra-db-data-2:
  cassandra-db-data-3: