version: '3.5'

services:
  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    command: redis-cli -p 7001 --cluster create 172.25.0.3:6379 172.25.0.4:6379 172.25.0.5:6379 172.25.0.6:6379 172.25.0.7:6379 172.25.0.8:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redis_network:
        ipv4_address: 172.25.0.2

  redis-1:
    image: redis:latest
    container_name: redis-1
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.3

  redis-2:
    image: redis:latest
    container_name: redis-2
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.4

  redis-3:
    image: redis:latest
    container_name: redis-3
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.5

  redis-4:
    image: redis:latest
    container_name: redis-4
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.6

  redis-5:
    image: redis:latest
    container_name: redis-5
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.7

  redis-6:
    image: redis:latest
    container_name: redis-6
    command: redis-server /etc/redis/redis.conf
    volumes:
      - "${PWD}/redis.conf:/etc/redis/redis.conf"
    networks:
      redis_network:
        ipv4_address: 172.25.0.8

networks:
  redis_network:
    ipam:
      config:
        - subnet: 172.25.0.0/24
